// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/Layout/components/AppMain.vue')['default']
    BreadCrumb: typeof import('./src/components/Layout/components/Navbar/BreadCrumb.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GDialog: typeof import('./src/components/dialog/GDialog.vue')['default']
    Hamburger: typeof import('./src/components/Layout/components/Navbar/Hamburger.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    Logo: typeof import('./src/components/Layout/components/Sidebar/Logo.vue')['default']
    Navbar: typeof import('./src/components/Layout/components/Navbar/Navbar.vue')['default']
    RightMenu: typeof import('./src/components/Layout/components/Navbar/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/components/Sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/Layout/components/Sidebar/SidebarItem.vue')['default']
    SidebarItemIcon: typeof import('./src/components/Layout/components/Sidebar/SidebarItemIcon.vue')['default']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    TagsView: typeof import('./src/components/Layout/components/TagsView/TagsView.vue')['default']
  }
}
